basePath: /api
definitions:
  github_com_ZaphCode_clean-arch_src_api_dtos.None:
    type: object
  github_com_ZaphCode_clean-arch_src_api_dtos.RespDetailErr:
    properties:
      detail:
        type: string
      message:
        type: string
      status:
        type: string
    type: object
  github_com_ZaphCode_clean-arch_src_api_dtos.RespErr:
    properties:
      message:
        type: string
      status:
        type: string
    type: object
  github_com_ZaphCode_clean-arch_src_api_dtos.RespOK-github_com_ZaphCode_clean-arch_src_api_dtos_None:
    properties:
      data:
        $ref: '#/definitions/github_com_ZaphCode_clean-arch_src_api_dtos.None'
      message:
        type: string
      status:
        type: string
    type: object
  github_com_ZaphCode_clean-arch_src_api_dtos.RespOK-github_com_ZaphCode_clean-arch_src_api_dtos_SignInResp:
    properties:
      data:
        $ref: '#/definitions/github_com_ZaphCode_clean-arch_src_api_dtos.SignInResp'
      message:
        type: string
      status:
        type: string
    type: object
  github_com_ZaphCode_clean-arch_src_api_dtos.RespOK-github_com_ZaphCode_clean-arch_src_domain_User:
    properties:
      data:
        $ref: '#/definitions/github_com_ZaphCode_clean-arch_src_domain.User'
      message:
        type: string
      status:
        type: string
    type: object
  github_com_ZaphCode_clean-arch_src_api_dtos.RespOK-string:
    properties:
      data:
        type: string
      message:
        type: string
      status:
        type: string
    type: object
  github_com_ZaphCode_clean-arch_src_api_dtos.RespValErr:
    properties:
      errors:
        items:
          $ref: '#/definitions/github_com_ZaphCode_clean-arch_src_services_validation.FieldError'
        type: array
      message:
        type: string
      status:
        type: string
    type: object
  github_com_ZaphCode_clean-arch_src_api_dtos.SignInResp:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
      user:
        $ref: '#/definitions/github_com_ZaphCode_clean-arch_src_domain.User'
    type: object
  github_com_ZaphCode_clean-arch_src_api_dtos.SigninDTO:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  github_com_ZaphCode_clean-arch_src_api_dtos.SignupDTO:
    properties:
      age:
        minimum: 15
        type: integer
      email:
        type: string
      password:
        minLength: 8
        type: string
      username:
        maxLength: 15
        minLength: 4
        type: string
    required:
    - age
    - email
    - password
    - username
    type: object
  github_com_ZaphCode_clean-arch_src_domain.User:
    properties:
      age:
        type: integer
      created_at:
        type: integer
      customer_id:
        type: string
      email:
        type: string
      id:
        type: string
      image_url:
        type: string
      role:
        type: string
      updated_at:
        type: integer
      username:
        type: string
      verified_email:
        type: boolean
    type: object
  github_com_ZaphCode_clean-arch_src_services_validation.FieldError:
    properties:
      field:
        type: string
      message:
        type: string
    type: object
host: localhost:9000
info:
  contact: {}
  description: This is a sample server celler server.
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: 1.6.9
paths:
  /auth/{provider}/callback:
    get:
      consumes:
      - application/json
      description: Sing in by OAuth provider (google/github/discord)
      parameters:
      - description: OAuth code
        in: query
        name: code
        required: true
        type: string
      - description: OAuth provider
        in: path
        name: provider
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_ZaphCode_clean-arch_src_api_dtos.RespOK-github_com_ZaphCode_clean-arch_src_api_dtos_SignInResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_ZaphCode_clean-arch_src_api_dtos.RespErr'
        "406":
          description: Not Acceptable
          schema:
            $ref: '#/definitions/github_com_ZaphCode_clean-arch_src_api_dtos.RespDetailErr'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_ZaphCode_clean-arch_src_api_dtos.RespDetailErr'
      summary: Sign in OAuth
      tags:
      - auth
  /auth/{provider}/url:
    get:
      consumes:
      - application/json
      description: Get OAuth url from provider (google/github/discord)
      parameters:
      - description: OAuth provider
        in: path
        name: provider
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_ZaphCode_clean-arch_src_api_dtos.RespOK-string'
        "406":
          description: Not Acceptable
          schema:
            $ref: '#/definitions/github_com_ZaphCode_clean-arch_src_api_dtos.RespDetailErr'
      summary: Get OAuth url
      tags:
      - auth
  /auth/me:
    get:
      consumes:
      - application/json
      description: Get the current authenticated user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_ZaphCode_clean-arch_src_api_dtos.RespOK-github_com_ZaphCode_clean-arch_src_domain_User'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_ZaphCode_clean-arch_src_api_dtos.RespErr'
      summary: Get auth user
      tags:
      - auth
  /auth/refresh:
    get:
      consumes:
      - application/json
      description: Refresh access jwtoken
      parameters:
      - description: Send refresh token method
        in: query
        name: method
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_ZaphCode_clean-arch_src_api_dtos.RespOK-string'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_ZaphCode_clean-arch_src_api_dtos.RespErr'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/github_com_ZaphCode_clean-arch_src_api_dtos.RespDetailErr'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_ZaphCode_clean-arch_src_api_dtos.RespDetailErr'
      summary: Refresh token
      tags:
      - auth
  /auth/signin:
    post:
      consumes:
      - application/json
      description: Login user
      parameters:
      - description: Sign in user
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/github_com_ZaphCode_clean-arch_src_api_dtos.SigninDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_ZaphCode_clean-arch_src_api_dtos.RespOK-github_com_ZaphCode_clean-arch_src_api_dtos_SignInResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_ZaphCode_clean-arch_src_api_dtos.RespValErr'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/github_com_ZaphCode_clean-arch_src_api_dtos.RespErr'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_ZaphCode_clean-arch_src_api_dtos.RespErr'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/github_com_ZaphCode_clean-arch_src_api_dtos.RespDetailErr'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_ZaphCode_clean-arch_src_api_dtos.RespDetailErr'
      summary: Sign in
      tags:
      - auth
  /auth/signout:
    get:
      description: Logout user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_ZaphCode_clean-arch_src_api_dtos.RespOK-github_com_ZaphCode_clean-arch_src_api_dtos_None'
      summary: Sign out
      tags:
      - auth
  /auth/signup:
    post:
      consumes:
      - application/json
      description: Register new user
      parameters:
      - description: Sign up user
        in: body
        name: user_data
        required: true
        schema:
          $ref: '#/definitions/github_com_ZaphCode_clean-arch_src_api_dtos.SignupDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_ZaphCode_clean-arch_src_api_dtos.RespOK-github_com_ZaphCode_clean-arch_src_domain_User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_ZaphCode_clean-arch_src_api_dtos.RespValErr'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/github_com_ZaphCode_clean-arch_src_api_dtos.RespDetailErr'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_ZaphCode_clean-arch_src_api_dtos.RespDetailErr'
      summary: Sign up
      tags:
      - auth
swagger: "2.0"
